const ActionTypes = {
  CREATE_WORKOUT: 'CREATE_WORKOUT',
  DELETE_WORKOUT: 'DELETE_WORKOUT',
  SELECT_WORKOUT: 'SELECT_WORKOUT',

  ADD_EXERCISE: 'ADD_EXERCISE',
  REMOVE_EXERCISE: 'REMOVE_EXERCISE',

  RECORD_SET: 'RECORD_SET',
  EDIT_SET: 'EDIT_SET',
};

export default ActionTypes;
